<bug id='5211' author='ReyRen' open_date='2020-08-13T09:08:41Z' closed_time='2020-08-20T06:07:00Z'>
	<summary>upstream connect error or disconnect/reset before headers. reset reason: connection failure</summary>
	<description>
/kind bug
What steps did you take and what happened:
[A clear and concise description of what the bug is.]
I following the doc installed the kubeflow, and all of those pods are at RUNNING status.
But, when I create a Notebook Servers, which use a custome image, pods startup and keep RUNNING status. Then I try to click "connect" in Notebook Servers, the error would occur with upstream connect error or disconnect/reset before headers. reset reason: connection failure. And get 503 response.
PS: I give sufficient resources (cpu:8, mem:20Gi) for this server.
What did you expect to happen:
I'm not pretty sure what's next when I click "connect", but not like this at least.
Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
Environment:

Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
v1.0
kfctl version: (use kfctl version):
kfctl v1.0.2-0-ga476281
Kubernetes platform: (e.g. minikube)
not the minikube
Kubernetes version: (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

	</description>
	<comments>
		<comment id='1' author='ReyRen' date='2020-08-13T09:08:49Z'>
		Issue-Label Bot is automatically applying the labels:



Label
Probability




area/jupyter
0.65



Please mark this comment with  or  to give our bot feedback!
Links: &lt;denchmark-link:https://github.com/marketplace/issue-label-bot&gt;app homepage&lt;/denchmark-link&gt;
, &lt;denchmark-link:https://label-bot-prod.mlbot.net/data/kubeflow/kubeflow&gt;dashboard&lt;/denchmark-link&gt;
 and &lt;denchmark-link:https://github.com/hamelsmu/MLapp&gt;code&lt;/denchmark-link&gt;
 for this bot.
		</comment>
		<comment id='2' author='ReyRen' date='2020-08-13T09:08:49Z'>
		Issue Label Bot is not confident enough to auto-label this issue.
See &lt;denchmark-link:https://label-bot-prod.mlbot.net/data/kubeflow/kubeflow&gt;dashboard&lt;/denchmark-link&gt;
 for more details.
		</comment>
		<comment id='3' author='ReyRen' date='2020-08-19T11:09:12Z'>
		need help, thanks
		</comment>
		<comment id='4' author='ReyRen' date='2020-08-20T06:07:00Z'>
		Ok, those image need to be customized. Refer to &lt;denchmark-link:https://www.kubeflow.org/docs/notebooks/custom-notebook/&gt;Create a Custom Jupyter Image&lt;/denchmark-link&gt;

closed
		</comment>
	</comments>
</bug>