<bug id='1243' author='isaacmg' open_date='2020-09-17T20:17:48Z' closed_time='2020-09-18T03:24:10Z'>
	<summary>Wandb sweep hanging on Google Colab</summary>
	<description>
wandb --version &amp;&amp; python --version &amp;&amp; uname

Weights and Biases version: 0.10.1
Python version: Python 3.6.9
Operating System: Google Colab

&lt;denchmark-h:h3&gt;Description&lt;/denchmark-h&gt;

Trying to run a sweep on Google Colab.
&lt;denchmark-h:h3&gt;What I Did&lt;/denchmark-h&gt;

So there is no error the sweep just hangs indefinitely after the first run.
&lt;denchmark-code&gt;wandb: Agent Finished Run
&lt;/denchmark-code&gt;

I then have to kill it manually
&lt;denchmark-code&gt;wandb: Ctrl-c pressed. Waiting for runs to end. Press ctrl-c again to terminate them.
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/wandb_agent.py", line 69, in _start
    run._stop_jupyter_agent()
AttributeError: 'Run' object has no attribute '_stop_jupyter_agent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.6/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
&lt;/denchmark-code&gt;

This is true even on relatively simple things:
&lt;denchmark-link:https://colab.research.google.com/drive/1u2xHJI_z-XoLTeFYGRzYS5PjdZGRakyG#scrollTo=HMRG0EnyyJYD&gt;https://colab.research.google.com/drive/1u2xHJI_z-XoLTeFYGRzYS5PjdZGRakyG#scrollTo=HMRG0EnyyJYD&lt;/denchmark-link&gt;

I also tested just using a generic train function with no model and it still fails.
&lt;denchmark-link:https://colab.research.google.com/drive/1Ek-BpLf6BTXaZORGhgAi3NZo07mMw9nO#scrollTo=SAqGr4Vjp6ml&gt;https://colab.research.google.com/drive/1Ek-BpLf6BTXaZORGhgAi3NZo07mMw9nO#scrollTo=SAqGr4Vjp6ml&lt;/denchmark-link&gt;

	</description>
	<comments>
		<comment id='1' author='isaacmg' date='2020-09-17T20:17:51Z'>
		Issue-Label Bot is automatically applying the label bug to this issue, with a confidence of 0.95. Please mark this comment with üëç or üëé to give our bot feedback!
Links: &lt;denchmark-link:https://github.com/marketplace/issue-label-bot&gt;app homepage&lt;/denchmark-link&gt;
, &lt;denchmark-link:https://mlbot.net/data/wandb/client&gt;dashboard&lt;/denchmark-link&gt;
 and &lt;denchmark-link:https://github.com/hamelsmu/MLapp&gt;code&lt;/denchmark-link&gt;
 for this bot.
		</comment>
		<comment id='2' author='isaacmg' date='2020-09-17T21:44:21Z'>
		Hey &lt;denchmark-link:https://github.com/isaacmg&gt;@isaacmg&lt;/denchmark-link&gt;
 we're aware of the issue.  With 0.10.1 you can use an experimental agent by replacing  with  which should fix the stalling issue.
		</comment>
		<comment id='3' author='isaacmg' date='2020-09-18T03:24:09Z'>
		Thanks. BTW for those wondering what the import statement looks like it is from wandb.jupyteragent import jupyteragent as _secretagent
		</comment>
	</comments>
</bug>