<bug id='12187' author='sunghopark98' open_date='2020-10-06T21:39:54Z' closed_time='2020-10-15T05:13:28Z'>
	<summary>LostStorageIntegrationTest failure on user 'root'</summary>
	<description>
Alluxio Version:
2.3.1
Describe the bug
I noticed that when I run the LostStorageIntegrationTest in root user, the reportLostStorageInWorkerRegister() and lostStorageWhenRestart() fail because the setReadOnly() for the ssdDir and hddDir doesn't stop the root user from creating the directory "/alluxioworker".
I believe this isn't a flaky test reason as I have deep dived to check the temporary directory that is created in these tests, and I saw the directory /alluxioworker inside of it when it should've been readonly.
To Reproduce
Switch user to "root" or whichever is the most parent user on machine:
sudo su - root
and then run
mvn clean install -DskipTests (if not built yet)
mvn test -Dtest=LostStorageIntegrationTest -pl tests
Expected behavior
&lt;denchmark-code&gt;Failed tests:
alluxio.server.tieredstore.LostStorageIntegrationTest.reportLostStorageInWorkerRegister(alluxio.server.tieredstore.LostStorageIntegrationTest)
  Run 1: LostStorageIntegrationTest.reportLostStorageInWorkerRegister:68-&gt;checkLostStorageResults:148 expected:&lt;1&gt; but was:&lt;0&gt;
  Run 2: LostStorageIntegrationTest.reportLostStorageInWorkerRegister:68-&gt;checkLostStorageResults:148 expected:&lt;1&gt; but was:&lt;0&gt;
Tests in error:
alluxio.server.tieredstore.LostStorageIntegrationTest.lostStorageWhenRestart(alluxio.server.tieredstore.LostStorageIntegrationTest)
  Run 1: LostStorageIntegrationTest.lostStorageWhenRestart:102-&gt;checkLostStorageResults:151 NullPointer
  Run 2: LostStorageIntegrationTest.lostStorageWhenRestart:102-&gt;checkLostStorageResults:151 NullPointer
&lt;/denchmark-code&gt;

Urgency
Not urgent
Additional context
This does not become an issue on normal 'user's since the directory is successfully 'readonly'
	</description>
	<comments>
		<comment id='1' author='sunghopark98' date='2020-10-08T23:01:26Z'>
		thanks &lt;denchmark-link:https://github.com/sunghopark98&gt;@sunghopark98&lt;/denchmark-link&gt;
 for reporting this issue
		</comment>
		<comment id='2' author='sunghopark98' date='2020-10-11T00:41:35Z'>
		&lt;denchmark-link:https://github.com/sunghopark98&gt;@sunghopark98&lt;/denchmark-link&gt;
 Thanks for reporting this issue, I've reproduced this issue.
		</comment>
		<comment id='3' author='sunghopark98' date='2020-10-14T06:26:21Z'>
		&lt;denchmark-link:https://github.com/sunghopark98&gt;@sunghopark98&lt;/denchmark-link&gt;
 Glad to share that I've correct this failure test.
I'd like to share one idea that we can use mock technology to instead of real method call, something like this issue, root user is a super user so it can disregard the permission, so by using powermock, the test result can be same no master which user executed this test.
		</comment>
	</comments>
</bug>