<bug id='270' author='jes08701' open_date='2019-10-02T18:10:10Z' closed_time='2020-06-16T00:01:44Z'>
	<summary>Wrong number of items passed</summary>
	<description>
Hi,
Not sure if this is a bug, though my dataset seems to be working well with other packages.  I keep getting the error message: 'Wrong number of items passed 103, placement implies 102', or some variant of that.
On occasion, the error changes to 'tuple index out of range'
I'm dealing with proprietary data and can't seem to reproduce this error with smaller sample datasets; my data is basically about 90,000 rows and 100 columns of binary (0 or 1) info.  Any advice?
Thanks!
	</description>
	<comments>
		<comment id='1' author='jes08701' date='2019-10-23T08:27:14Z'>
		Hi,
I experience exactly the same issue. However, my dataset is much smaller:
100 rows and 58 columns (of which 54 columns contain binary data). This results in the following value error:
'Wrong number of items passed 57, placement implies 55'
When I run the pandas-profiling without the columns containing binary data it performs without any errors.
update: when replacing 0 and 1 with "no" and "yes" the report is processed succesfully.
		</comment>
		<comment id='2' author='jes08701' date='2020-02-15T00:01:25Z'>
		Stale issue
		</comment>
		<comment id='3' author='jes08701' date='2020-02-19T19:20:08Z'>
		Hi,
same issue for me. I have a dataset of 22222 observations and 124 variables, many of them are dummies. I use pandas 0.25.3, python 3.8 and pandas_profiling 0.25.
I noticed that the problem occurs, if my bool variables are stored as integers. If I convert them to bool or string, it solves the issue.
		</comment>
		<comment id='4' author='jes08701' date='2020-02-27T08:04:01Z'>
		is there a better solution for this? or is it a bug with boolean features for now? facing the exact same issues
		</comment>
		<comment id='5' author='jes08701' date='2020-04-08T14:18:33Z'>
		I have a weird solution for you. In fact, this error is floating. So you can brute force it by calling it again and again until it won't succeed.
for i in range(100):
    try:
        pr = ProfileReport(your_data_set)
        print('Finally worked')
        break
    except:
        continue
This worked for me.
		</comment>
		<comment id='6' author='jes08701' date='2020-06-08T00:01:47Z'>
		Stale issue
		</comment>
	</comments>
</bug>