<bug_data>
<bug id='14739' author='malmaud' open_date='2017-11-21T02:31:54Z' closed_time='2017-12-02T09:39:46Z'>
 	<summary>Eager: Warn with invalid policy</summary>
 	<description>
 If a user accidentally writes tfe.enable_eager_execution(tfe.DEVICE_PLACEMENT_WARN) instead of the correct tfe.enable_eager_execution(device_policy=tfe.DEVICE_PLACEMENT_WARN), they won't get an error until later in their program.
 For example, tfe.num_gpus() after  the incorrect enable call produces
 &lt;denchmark-code&gt;---------------------------------------------------------------------------
 AttributeError                            Traceback (most recent call last)
 &lt;ipython-input-8-71d6509178f5&gt; in &lt;module&gt;()
 ----&gt; 1 tfe.num_gpus()
 
 ~/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/context.py in num_gpus()
     458     The number of available GPU devices.
     459   """
 --&gt; 460   return context().num_gpus()
 
 ~/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/context.py in num_gpus(self)
     286   def num_gpus(self):
     287     """The number of GPUs available to execute operations."""
 --&gt; 288     self._initialize_handle_and_devices()
     289     return self._num_gpus
     290 
 
 ~/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/context.py in _initialize_handle_and_devices(self)
     121         with errors.raise_exception_on_not_ok_status() as status:
     122           if self._config is not None:
 --&gt; 123             config_str = self._config.SerializeToString()
     124             pywrap_tensorflow.TFE_ContextOptionsSetConfig(
     125                 opts, config_str, len(config_str), status)
 
 AttributeError: 'int' object has no attribute 'SerializeToString'
 &lt;/denchmark-code&gt;
 
 I'd think it makes more sense to throw an error immediately after the incorrect enable_eager_execution.
 This is on  (&lt;denchmark-link:https://github.com/tensorflow/tensorflow/commit/ab00df9b0b74910ca738e6ee850982f62ad42e55&gt;ab00df9&lt;/denchmark-link&gt;
 ).
 	</description>
 	<comments>
 		<comment id='1' author='malmaud' date='2017-11-25T06:31:40Z'>
 		&lt;denchmark-link:https://github.com/asimshankar&gt;@asimshankar&lt;/denchmark-link&gt;
  could you please take a look into this.
 		</comment>
 		<comment id='2' author='malmaud' date='2017-11-28T01:10:15Z'>
 		Sounds like a fair request :), will send out a change to address this.
 		</comment>
 	</comments>
 </bug>
<commit id='ba87a8030aa30f24c354cf705e79734658bb0a8b' author='Asim Shankar' date='2017-11-28 12:22:09-08:00'>
 	<dmm_unit complexity='0.375' interfacing='1.0' size='0.375'></dmm_unit>
 	<modification change_type='MODIFY' old_name='tensorflow\python\framework\ops.py' new_name='tensorflow\python\framework\ops.py'>
 		<file_info nloc='2596' complexity='645' token_count='13660'></file_info>
 		<method name='enable_eager_execution' parameters='config,device_policy'>
 				<method_info nloc='34' complexity='12' token_count='193' nesting_level='0' start_line='4764' end_line='4831'></method_info>
 			<added_lines>4798,4799,4800,4801,4802,4803,4804,4805,4806,4807</added_lines>
 			<deleted_lines></deleted_lines>
 		</method>
 		<modified_lines>
 			<added_lines>38</added_lines>
 			<deleted_lines></deleted_lines>
 		</modified_lines>
 	</modification>
 	<modification change_type='MODIFY' old_name='tensorflow\python\framework\ops_test.py' new_name='tensorflow\python\framework\ops_test.py'>
 		<file_info nloc='1931' complexity='203' token_count='17290'></file_info>
 		<method name='testBadArgumentsToEnableEagerExecution' parameters='self'>
 				<method_info nloc='6' complexity='1' token_count='48' nesting_level='1' start_line='2398' end_line='2403'></method_info>
 			<added_lines>2398,2399,2400,2401,2402,2403</added_lines>
 			<deleted_lines></deleted_lines>
 		</method>
 		<modified_lines>
 			<added_lines>2404</added_lines>
 			<deleted_lines></deleted_lines>
 		</modified_lines>
 	</modification>
 </commit>
</bug_data>
